---
title: "Database Schema"
config:
  theme: base
---
erDiagram

  classDef strong_entity stroke:#283593;
  classDef subtype stroke:#1976D2;
  classDef weak_entity stroke:#1976D2;
  classDef unknown stroke:#AAAAAA;
  classDef non_entity stroke:#AAAAAA;

  "PUBLIC.BOOKS.AUTHORS":::strong_entity {
    string FIRSTNAME
    string LASTNAME
    string ADDRESS1
    string ADDRESS2
    string CITY
    string STATE
    string POSTALCODE
    string COUNTRY
  }

  "PUBLIC.BOOKS.BOOKS":::strong_entity {
    string TITLE "Book title"
    string DESCRIPTION "Book description (Usually the blurb from the book jacket or promotional materials)"
    integer PUBLISHERID "Foreign key to the book publisher"
    date PUBLICATIONDATE "Book publication date"
    decimal PRICE "Current price for the book"
  }

  "PUBLIC.BOOKS.AUTHORS" }o--o{ "PUBLIC.BOOKS.BOOKS" : "via bridge table BOOKAUTHORS"